apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    kompose.cmd: C:\Program Files\KomposeTool\kompose.exe convert -o istio-test-deployment.yaml
    kompose.service.type: loadbalancer
    kompose.version: 1.4.0 (c7964e7)
  name: istio-test-virtualservice
  namespace: istio-apps
spec:
  hosts:
  - "*"
  gateways:
  - istio-test-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: istio-test
        port:
          number: 5000
